### PR TITLE
small typos in chapter 5 to 7

### PR DESCRIPTION
**Pull request by tlossen**

### CODE REVIEW

**Comment by hintjens** [comment]
I'm afraid I renumbered the chapters and made some edits... if you pull the repo again you should get a working merge.

**Comment by tlossen** [comment]
ok, i see.

**Comment by tlossen** [comment]
no, the merge is a trainwreck. i'll enter the corrections tomorrow again.

**Comment by hintjens** [comment]
Yeah, sorry about that. I do appreciate the fixes. I've pushed a few more edits, in case you want to fetch master again.

**Comment by tlossen** [comment]
i�ll just make a fresh clone before i start :)

**Pull request closed without merging**
